### ISSUE TITLE
silently crash when forgot to add global module hook

### ISSUE THREAD

**Issue by sisisin** [typeless-js/typeless#6]
### reproduction

- delete this line
https://github.com/typeless-js/create-react-app-starter/blob/de84a6a4d4e29c4736620b86c7bf23b95858bddc/src/components/App.tsx#L31
- `yarn start`

### expected behavior

- output error message

### actual behavior

- silently crashed

**Comment by BetterCallSky** [comment]
Hello @sisisin,

There are no errors, and it works as expected.
If `useGlobalModule` is not loaded, then `isLoaded` is undefined because `state.global` is undefined as well.  
RouteResolver won't be loaded in this line `{isLoaded && <RouteResolver />}`.
It just displays a blank page.

Try to change `{isLoaded && <RouteResolver />}` to `{isLoaded ? <RouteResolver /> : 'loading'}`, and you will see the text.

**Comment by sisisin** [comment]
thx for your answer, I understand my mistake!
